version: '3'
services:
  axon_server:
    image: axoniq/axonserver
    container_name: axon_server
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      - AXONIQ_AXONSERVER_NAME=order_demo